#!/usr/bin/env python3

import sys
sys.path.insert(0, 'src')
from shell import *

def fail(s):
    sys.stderr.write('TEST FAILURE!\n\n')
    sys.stderr.write(s)
    sys.stderr.write('\n')
    sys.exit(1)

def checkOutput(out, lines):
    idx = 0
    for x in out.split('\n'):
        if idx >= len(lines):
            return
        x = x.strip()
        if x.startswith(lines[idx]):
            idx = idx + 1
    if idx < len(lines):
        unmatched = lines[idx:]
        fail(f"""The following lines weren't found in the output: {unmatched}
Output:
{out}
""")

print('Unit tests')
print('==========')
run('./unit-tests')

print()
print('Integration tests')
print('=================')
res = run('python3 tests/integration-test.py', captureStdout=True).stdout
checkOutput(res, [
    'FAIL: test_foo',
    'AssertionError: 41 != 42',
    'TutorTest > testBar() FAILED',
    'org.opentest4j.AssertionFailedError: expected: <1> but was: <0>',
    'BUILD SUCCESSFUL'
])
print('OK')
